### ISSUE TITLE
HCM crashes when attempting to install an external over a non externalled component.

### ISSUE THREAD

**Issue by jeremiah-c-leary** [jeremiah-c-leary/hdl-component-manager#41]
comps$ hcm install bishop
INFO:Installing component bishop
INFO:Validating all files for component bishop are committed.
INFO:Removing local component directory
INFO:Installation complete
comps$ hcm list

Component     Version      Upgrade      Status     URL                                    
---------     --------     --------     ------     ---------------------------------------
bishop        2.0.0        None           U        file:///home/jeremiah/svn/my_repo/comps
queen         3.0.0        None         E          file:///home/jeremiah/svn/my_repo/comps
rook          3.0.0        4.0.0        E          file:///home/jeremiah/svn/my_repo/comps
comps$ svn status
 M      .
A  +    bishop
X       queen
X       rook

Performing status on external item at 'queen':

Performing status on external item at 'rook':
comps$ hcm install bishop --external
INFO:Installing component bishop
INFO:Validating all files for component bishop are committed.
ERROR:The following files must be committed or removed:
A  +    bishop
comps$ hcm install bishop --external --force
INFO:Installing component bishop
INFO:Removing local component directory
INFO:Updating externals
Traceback (most recent call last):
  File "/home/jeremiah/projects/hdl-component-manager/bin/hcm", line 14, in <module>
    main()
  File "/home/jeremiah/projects/hdl-component-manager/bin/../hcm/__main__.py", line 128, in main
    subcommand.install(commandLineArguments)
  File "/home/jeremiah/projects/hdl-component-manager/bin/../hcm/subcommand/install.py", line 12, in install
    install_component(oCommandLineArguments)
  File "/home/jeremiah/projects/hdl-component-manager/bin/../hcm/subcommand/install.py", line 76, in install_component
    svn.issue_command(['svn', 'update', '.'])
  File "/home/jeremiah/projects/hdl-component-manager/bin/../hcm/svn.py", line 10, in issue_command
    raise e
subprocess.CalledProcessError: Command '['svn', 'update', '.']' returned non-zero exit status 1

**Comment by jeremiah-c-leary** [comment]
If I reverted the component, then I could update and get the external populated.
The component was added, but not committed.
I am not sure if that makes a difference.

**Comment by jeremiah-c-leary** [comment]
In order for this to work, the directory must be deleted and committed before the external can be made.
This seems outside the scope of HCM.
I will make HCM throw an error though if this condition is encountered.
